{
 "title": "User Session Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Computername",
    "label": "ComputerName",
    "query": "{\"find\": \"terms\", \"field\": \"host\", \"size\": 10000}"
   },
   { "name": "CustomFilter", "label": "Custom Filter" }
  ]
 },
 "panels": [
  {
   "title": "Session Detail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "host", "id": "2", "settings": { "order": "desc", "orderBy": "_term", "size": "10" }, "type": "terms" }
     ],
     "metrics": [
      {
       "field": "host",
       "hide": false,
       "id": "1",
       "type": "cardinality"
      },
      { "field": "SessionUser", "id": "3", "type": "cardinality" },
      { "field": "SessionGUID", "id": "4", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "User Sessions over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "SessionGUID", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average logon duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TotalLogoffTimeMs", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}