{
 "title": "Application Details",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "AppName" },
   {
    "name": "Computername",
    "label": "ComputerName",
    "query": "{\"find\": \"terms\", \"field\": \"host\", \"size\": 10000}"
   },
   { "name": "CustomFilter", "label": "Custom Filter" }
  ]
 },
 "panels": [
  {
   "title": "Install count per Application (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "DisplayName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "host", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Install count per Publisher (Top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Publisher",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "host", "id": "1", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Inventory",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Publisher",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "DisplayName",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1000" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "host", "id": "1", "type": "cardinality" },
      { "field": "DisplayVersion", "id": "4", "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Detail",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "DisplayName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "DisplayVersion",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "InstallLocation",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "DisplayVersion",
       "hide": false,
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "DisplayName:$AppName*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}