{
 "title": "Application Errors",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Application Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Sourcetype",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Crashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Sourcetype",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\" AND ErrorType:1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Hang",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Sourcetype",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\" AND ErrorType:2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Errors by ComputerName",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Errors by User",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ProcUser",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Crashes",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ProcName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "ProcVersion",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "ExceptionCode",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "ModuleName",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "AppId",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "ProcUser", "id": "3", "type": "cardinality" },
      { "field": "host", "id": "4", "type": "cardinality" },
      { "field": "ProcLifetimeMs", "id": "5", "type": "avg" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\" AND ErrorType:1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Hangs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ProcName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "ProcVersion",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ExceptionCode",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ModuleName",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "AppId",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "ProcUser", "id": "3", "type": "cardinality" },
      { "field": "host", "id": "4", "type": "cardinality" },
      { "field": "ProcLifetimeMs", "id": "5", "type": "avg" }
     ],
     "query": "Sourcetype:\"uberAgent:Application:Errors\" AND ErrorType:2",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}