{
 "title": "Machine Performance (Top 25)",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Avg CPU Usage per Machine",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "CPUUsagePercent", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg RAM Usage per Machine (%)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "RAMUsagePercent", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RAM Usage per Machine (GB)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "RAMUsageGB", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg Network Usage per Machine (%)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "NetUtilizationPercent", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg Disk IO per Machine (%)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "IOPercentDiskTime", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg GPU Memory Usage (MB)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "MemorySharedMB", "id": "1", "type": "avg" },
      { "field": "MemoryDedicatedMB", "id": "3", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Machine Performance",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "CPUUsagePercent", "id": "1", "type": "avg" },
      { "field": "IOPS", "id": "3", "type": "avg" },
      { "field": "IOPercentDiskTime", "id": "4", "type": "avg" },
      { "field": "IOLatencyMs", "id": "5", "type": "avg" },
      { "field": "RAMUsageGB", "id": "6", "type": "avg" },
      { "field": "RAMUsagePercent", "id": "7", "type": "avg" },
      { "field": "NetUtilizationPercent", "id": "8", "type": "avg" },
      { "field": "KernelPagedMB", "id": "9", "type": "avg" },
      { "field": "KernelNonPagedMB", "id": "10", "type": "avg" },
      { "field": "HandleCount", "id": "11", "type": "avg" },
      { "field": "ThreadCount", "id": "12", "type": "avg" },
      { "field": "CPURelativeFrequencyPercent", "id": "13", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}