{
 "title": "User Session Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Computername",
    "label": "ComputerName",
    "query": "{\"find\": \"terms\", \"field\": \"host\", \"size\": 10000}"
   },
   { "name": "CustomFilter", "label": "Custom Filter" }
  ]
 },
 "panels": [
  {
   "title": "User Sessions over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "5m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "SessionGUID", "id": "1", "type": "cardinality" }
     ],
     "query": "host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average logon duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "TotalLogoffTimeMs", "id": "1", "type": "sum" }
     ],
     "query": "host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Time (top 10)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "SessionUser",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "SessionCPUTimeMs", "id": "1", "type": "sum" }
     ],
     "query": "host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RAM Usage (top 10)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "SessionUser",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "SessionWorkingSetMB", "id": "1", "type": "avg" }
     ],
     "query": "host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IO Count (top 10)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "SessionUser",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "SessionIOCount", "id": "1", "type": "sum" }
     ],
     "query": "host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Active Session List",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "SessionUser",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "host",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "SessionProtocol",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "SessionLogonTime",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "SessionID",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "SessionProcessCount", "id": "1", "type": "avg" },
      { "field": "SessionCPUUsagePercent", "id": "3", "type": "avg" },
      { "field": "SessionIOLatencyMs", "id": "4", "type": "avg" },
      { "field": "SessionIOMB", "id": "5", "type": "avg" },
      { "field": "SessionIOCount", "id": "6", "type": "sum" },
      { "field": "SessionWorkingSetMB", "id": "7", "type": "avg" },
      { "field": "SessionNetKBPS", "id": "12", "type": "avg" }
     ],
     "query": "SessionConnectionState:active AND host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disconnected Session List",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "SessionUser",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "host",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      {
       "field": "SessionLogonTime",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "SessionID",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "SessionProcessCount", "id": "1", "type": "avg" },
      { "field": "SessionCPUUsagePercent", "id": "3", "type": "avg" },
      { "field": "SessionIOLatencyMs", "id": "4", "type": "avg" },
      { "field": "SessionIOMB", "id": "5", "type": "avg" },
      { "field": "SessionIOCount", "id": "6", "type": "sum" },
      { "field": "SessionWorkingSetMB", "id": "7", "type": "avg" },
      { "field": "SessionNetKBPS", "id": "12", "type": "avg" }
     ],
     "query": "SessionConnectionState:disconnected AND host:$Computername AND NOT SessionUser:sys",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}